### PR TITLE
Add footer and claim address

### PR DESCRIPTION
**Pull request by moenaser4**
### Description

* Implemented Claim address component.
* Implemented Footer component.

### figma links:
ClaimAddress:
Desktop: https://www.figma.com/file/22d3bKcFL0ipWIZJOUY3Km/reverifi?node-id=0%3A3779
Mobile:  https://www.figma.com/file/22d3bKcFL0ipWIZJOUY3Km/reverifi?node-id=0%3A16338

Footer:
Desktop:https://www.figma.com/file/22d3bKcFL0ipWIZJOUY3Km/reverifi?node-id=0%3A3779
Mobile:https://www.figma.com/file/22d3bKcFL0ipWIZJOUY3Km/reverifi?node-id=0%3A16338

### CODE REVIEW

**Review by abukhadraop — CHANGES_REQUESTED** [review]
General notes
- we should use `rem` instead of `px` as CSS unit  except for border width
- all colors should be moved to the colors file
- lets try to keep the syles sorted alphabetically 
- we should keep an empty line between CSS blocks 
   ```js
    const Item = styled.div`
      ...
      // empty line
      p {
       ...
      }
     // empty line
      ${mq.tablet`
       ....
      `}
    `;
   ``` 
- try to avoid static width and height as much as possible, you can add spacing between elements using margin and padding and you can use min/max-height/width to restrict width and height 
- flex is not always the best solution, sometimes a simple dev with center text align could be much easier

**Review by MZeq — COMMENTED** [review]
Good job, however there are some mismatches and feature enhancements

- The gap between `Claim Your Address` header and the input bar doesn't match the design.
- If it's possible to replace all the span elements for the links to be actual links, e.g:  About us should redirect to `.../about-us` and so on, even if these pages are not implemented yet.
- Clicking anywhere on the input bar except for the buttons should focus the input field, `refs` and `onClick` events can be helpful in implementing this.
- Please adjust the spacing between `Start your real estate journey` and `reverifi` logo.
- For the email in the contact us section use [linkto](https://www.w3schools.com/tags/tag_address.asp) and add[`rel=noopener`](https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/noopener) attribute and read about why it's used.
- Add `aria-label` and `role` attributes for accessibility on all interactive elements (buttons/links..etc) with the correct values.
- Change the placeholder color to be a lighter shade of grey.

**Comment by MZeq** [comment]
Looking good, some few adjustments so we can merge this 🤞🏼

The links in the footer span the whole line

Screen Shot 2021-12-22 at 2 48 35 PM

And can we make the reverifi logo and list beneath align with the other adjacent lists?

Screen Shot 2021-12-22 at 2 50 50 PM

**Comment by MZeq** [comment]
This PR is going to be closed so we could change the name of the branch.
New PR at https://github.com/abukhadraop-or/reverifi/pull/14

**Pull request closed without merging**
